baseurl = "http://example.org"
title = "Tony Wingfield"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Website guy focused on increasing visibility, owner of <a href="https://dzines.co.uk">Dzines Digital</a> <!--]--><br />
                <!--[-->Web development, SEO, Video.<!--]-->'
  logo = "fa-cubes"
  copyright = "Tony Wingfield"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
